config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehiculos.urls')),
]

vehiculos/urls.py
from django.urls import path

from .views import index, v_add, v_list

urlpatterns = [path('', index), 
              path('vehiculo/add', v_add),
              path('vehiculo/list', v_list)]

vehiculos/models.py
from django.db import models



# Create your models here.
class Vehiculo(models.Model):
    marcas = [["@fiat", "Fiat"], 
              ["@chevrolet", "Chevrolet"], 
              ["@ford", "Ford"], 
              ["@toyota", "Toyota"]
             ]

    marca = models.CharField(max_length=20, choices = marcas, default ="@ford")
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)

    categorias = [["Particular", "Particular"], 
                  ["transporte", "transporte"], 
                  ["carga", "carga"]]
  
    categoria = models.CharField(max_length=20, choices= categorias, default="Particular")
    precio = models.DecimalField(max_digits=7,
                                 decimal_places=2,
                                 blank=False,
                                 null=False)

  #auto_now_add se añade una sola vez, cuando se crea el registro 
    creacion = models.DateTimeField(auto_now_add=True)
  #auto_now se modifica con cada cambio que se realiza el modelo 
    modificacion = models.DateTimeField(auto_now=True)


    class Meta:  
      permissions = [("visualizar_catalogo", "Visualizar catalogos")]

    def condicion_precio(self):
      if self.precio >= 0 and self.precio <= 10000:
        return "Bajo"
      elif self.precio >= 10001 and self.precio <= 30000:
        return "Medio"
      elif self.precio >= 30001:
        return "Alto"
      

vehiculos/forms.py
from django import forms
from .models import Vehiculo

class VehiculoForm(forms.ModelForm):
  class Meta:
    model = Vehiculo
    exclude = []
    

vehiculos/views.py
from django.shortcuts import render
from .forms import VehiculoForm
from .models import Vehiculo


# Create your views here.
def index(request):
    context = {}
    return render(request, "index.html", context)


from django.contrib.auth.decorators import login_required, permission_required


@login_required(login_url = "/admin/login/")
@permission_required('vehiculos.visualizar_catalogo', login_url = "/admin/login/")
def v_list(request):
    context = {'cars': Vehiculo.objects.all()}
    return render(request, "list.html", context)



@login_required(login_url="/admin/login/")
@permission_required('vehiculos.add_vehiculo', login_url = "/admin/login/")
def v_add(request):
    if request.method == 'POST':
        data = VehiculoForm(request.POST)
        if data.is_valid():
            data.save()

    context = {"form": VehiculoForm()}
    return render(request, "add.html", context)

config/templates/add.html
{% extends 'base.html' %}

{% block content %}
  <h1>Crear nuevo vehiculo</h1>
  <form method="POST">  
    {% csrf_token %}
    {{ form.as_p }}
    <button class"btn btn-primary" type="submit">Enviar</button>
  </form>
{% endblock %}

config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>Catalogo de vehiculos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>
  <body>
      <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark"> 
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Vehiculos</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
              {% if user.is_authenticated %}
<a class="nav-link active" aria-current="page" href="#">Hola, {{ user.username }}</a>
              {% endif %}
</li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Inicio</a>
          </li>
          <li class="nav-item" >
            <a class="nav-link" href="/vehiculo/list">Listar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/vehiculo/add">Agregar</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
  <div>
    <img src="https://img.freepik.com/vector-premium/energia-electrica-coche-banner-horizontal-hibrido-vechicle-carga-estacion-eco-friendly-auto-concept_48369-15396.jpg?w=2000" alt="Descripción de la imagen">
  </div>
</html>

config/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Catalogo de Productos</h1>
{% endblock %} 

config/templates/list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Catálogo de Vehiculos</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Serial Carroceria</th>
        <th>Serial Motor</th>
        <th>Categoria</th>
        <th>Precio</th>
        <th>Condicion de Precio</th>
      </tr>
    </thead>
    <tbody>
      {% for v in cars %}
      <tr>
        <td>{{ v.get_marca_display }}</td>
        <td>{{ v.modelo }}</td>
        <td>{{ v.serial_carroceria }}</td>
        <td>{{ v.serial_motor }}</td>
        <td>{{ v.categoria }}</td>
        <td>{{ v.precio }}</td>
        <td> {{ v.condicion_precio }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

      
      
      
    
        